### ISSUE TITLE
目次のリンク先がイケてない

### ISSUE THREAD

**Issue by noritama-vrc** [yuya-0928/Resume#6]
イケてないポイント
- そもそもURLが間違っていて「ページ移動しました」に飛ばされる
- そこから移転先に行ってもページ先頭に行かされる（目次の意味が無い）
- 目次なのにURLをフルで指定するのは冗長（ファイル構成変更で都度対応が必要）
- PDF化した場合に目次クリックで PDF → Github上のWeb Pageに飛ばされる

aタグ埋め込んでアンカーにするのが良いのでは？

aタグを埋め込んだmdをPDFに変換した場合に、目次からのアンカーリンクが効いてることは確認済み
この時のPDF変換は以下を使用
https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf
このRepositoryのPDF変換でもアンカーリンクが効くかの確認は別途必要

**Comment by noritama-vrc** [comment]
やっぱ権限無くてbranch切れない
ぐわ～

**Comment by yuni-shinogami** [comment]
生成されたPDFの目次からアンカーリンクが効いていることが確認できました！
こちらのIssueは解決してそうなのでCloseします。
ありがとうございました！
